Repository pickipi/loco_project, pull requests merged in 2025-06, with the labels that each got.

#161 [Fix/#160] 공간 상세페이지 및 공간 목록 인가 설정 수정
  backend/build.gradle.kts
  backend/src/main/java/com/likelion/loco_project/domain/space/controller/ApiV1SpaceController.java
  backend/src/main/java/com/likelion/loco_project/domain/space/entity/Space.java
  backend/src/main/java/com/likelion/loco_project/global/config/SecurityConfig.java
  frontend/src/app/spaces/[id]/page.tsx
Labels: fix

#166 feat: 개인정보 수정기능, 공간상세 페이지 헤더 추가
  frontend/src/app/mypage/change-password/page.tsx
  frontend/src/app/mypage/page.tsx
  frontend/src/app/spaces/[id]/page.tsx
  frontend/src/context/AuthContext.tsx
  frontend/src/lib/axios.ts
Labels: feature

#167 [Feature/#164] 예약 / 결제 상세 페이지 연동 및 토스 페이먼츠 테스트
  backend/src/main/java/com/likelion/loco_project/global/config/SecurityConfig.java
  frontend/.env
  frontend/src/app/payment/page.tsx
  frontend/src/app/reservation/page.tsx
  frontend/src/app/spaces/[id]/page.tsx
Labels: feature

#168 update: 호스트 회원가입시 호스트 db에 들어가게 (#149)
  backend/src/main/java/com/likelion/loco_project/domain/host/dto/HostRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/likelion/loco_project/global/oauth/OAuth2AuthenticationSuccessHandler.java
  frontend/src/app/host/profile/page.tsx
  frontend/src/app/host/signup/page.tsx
Labels: update

#172 [Feature/#117] 메인페이지 검색 기능 추가 및 검색 필터링 요소 구현
  backend/build.gradle.kts
  backend/src/main/java/com/likelion/loco_project/domain/space/controller/ApiV1SpaceController.java
  backend/src/main/java/com/likelion/loco_project/global/config/SecurityConfig.java
  frontend/public/default-space.jpg
  frontend/public/placeholder-banner.jpg
  frontend/public/placeholder-popular-1.jpg
  frontend/public/placeholder-popular-2.jpg
  frontend/public/placeholder-popular-3.jpg
  frontend/public/placeholder-studio.jpg
  frontend/public/placeholder.svg
  frontend/src/app/host/layout.tsx
  frontend/src/app/host/spaces/register/details/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/spaces/all/page.tsx
  frontend/src/app/spaces/page.tsx
  frontend/src/app/spaces/search/page.tsx
  frontend/src/components/header/header.tsx
  frontend/src/components/header/hostheader.tsx
  frontend/src/components/space/SpaceCard.tsx
  frontend/src/types/space.ts
Labels: feature
