Repository pickipi/loco_project, pull requests merged in 2025-05, with the labels that each got.

#8 [Feature/#7] Post -> Board 변경 및 엔티티, DTO 기초 틀 설계 완료
  backend/src/main/java/com/likelion/loco_project/domain/board/board/controller/ApiV1BoardController.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/dto/BoardDetailResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/dto/BoardListResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/dto/BoardRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/dto/BoardResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/entity/Board.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/entity/Category.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/repository/BoardRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/service/BoardService.java
  backend/src/main/java/com/likelion/loco_project/domain/board/post/entity/Post.java
  backend/src/main/java/com/likelion/loco_project/domain/board/post/repository/PostRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/board/post/service/PostService.java
  backend/src/main/java/com/likelion/loco_project/domain/host/entity/Host.java
  backend/src/main/java/com/likelion/loco_project/domain/space/entity/Space.java
Labels: feature

#12 [feature/#12] pr 다시보내기
  backend/src/main/java/com/likelion/loco_project/domain/chat/controller/ApiV1ChatController.java
  backend/src/main/java/com/likelion/loco_project/domain/space/entity/Space.java
Labels: feature

#14 [Feature/#7] Board 관련 엔티티, DTO, Repo, Service 설계 완료
  backend/src/main/java/com/likelion/loco_project/domain/board/board/controller/ApiV1BoardController.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/dto/BoardDetailResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/dto/BoardListResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/dto/BoardRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/dto/BoardResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/repository/BoardRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/service/BoardService.java
  backend/src/main/java/com/likelion/loco_project/domain/host/entity/Host.java
  backend/src/main/java/com/likelion/loco_project/domain/host/repository/HostRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/space/entity/Space.java
  backend/src/main/java/com/likelion/loco_project/domain/space/repository/SpaceRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/user/entity/User.java
  backend/src/main/java/com/likelion/loco_project/domain/user/repository/UserRepository.java
  backend/src/main/java/com/likelion/loco_project/global/config/SecurityConfig.java
  backend/src/main/java/com/likelion/loco_project/global/exception/AccessDeniedException.java
  backend/src/main/java/com/likelion/loco_project/global/exception/ResourceNotFoundException.java
Labels: feature

#17 [Feature/#16] 예약/결제 관련 엔티티, DTO, Repo, Service 설계 완료
  backend/src/main/java/com/likelion/loco_project/domain/payment/dto/PaymentDto.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/dto/PaymentRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/dto/PaymentResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/entity/Payment.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/entity/PaymentStatus.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/repository/PaymentRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/service/PaymentService.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/dto/ReservationDto.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/dto/ReservationRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/dto/ReservationResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/entity/Reservation.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/repository/ReservationRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/service/ReservationService.java
Labels: feature

#18 [Feature/#10] 공간 CRUD
  README.md
  backend/build.gradle.kts
  backend/src/main/java/com/likelion/loco_project/domain/chat/controller/ApiV1ChatController.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/dto/ChatMessageResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/entity/ChatMessage.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/entity/ChatRoom.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/repository/ChatMessageRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/service/ChatMessageService.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/service/ChatRoomService.java
  backend/src/main/java/com/likelion/loco_project/domain/space/controller/ApiV1SpaceController.java
  backend/src/main/java/com/likelion/loco_project/domain/space/dto/SpaceCreateRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/space/dto/SpaceDto.java
  backend/src/main/java/com/likelion/loco_project/domain/space/dto/SpaceResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/space/dto/SpaceUpdateRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/space/entity/Space.java
  backend/src/main/java/com/likelion/loco_project/domain/space/repository/SpaceRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/space/service/SpaceService.java
  backend/src/main/java/com/likelion/loco_project/global/rsData/RsData.java
  backend/src/main/resources/application.yml
Labels: feature

#19 [Feature/#6] 유저,어드민 / 회원가입 기능 및 보안 설정 구현완료, Admin 패키지 기본요소 추가
  backend/build.gradle.kts
  backend/src/main/java/com/likelion/loco_project/domain/admin/controller/AdminController.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/dto/AdminLoginRequest.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/entity/Admin.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/entity/AdminRole.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/repository/AdminRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/service/AdminService.java
  backend/src/main/java/com/likelion/loco_project/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/likelion/loco_project/domain/user/dto/UserRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/user/dto/UserResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/user/entity/User.java
  backend/src/main/java/com/likelion/loco_project/domain/user/entity/UserType.java
  backend/src/main/java/com/likelion/loco_project/domain/user/repository/UserRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/user/service/UserService.java
  backend/src/main/java/com/likelion/loco_project/global/config/AppConfig.java
Labels: feature

#22 [Feature/#15] Board Controller 설계 및 수정/삭제 메소드 추가
  backend/src/main/java/com/likelion/loco_project/domain/board/board/controller/ApiV1BoardController.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/dto/BoardDetailResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/dto/BoardRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/dto/BoardResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/entity/Board.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/service/BoardService.java
Labels: feature

#25 feat: 채팅, 공간 기능 추가(#20)
  backend/build.gradle.kts
  backend/src/main/java/com/likelion/loco_project/domain/chat/controller/ApiV1ChatController.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/dto/ChatMessageResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/dto/ChatMessageStompDto.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/entity/ChatMessage.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/entity/ChatRoom.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/repository/ChatRoomRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/service/ChatRoomService.java
  backend/src/main/java/com/likelion/loco_project/domain/space/controller/ApiV1SpaceController.java
  backend/src/main/java/com/likelion/loco_project/domain/space/dto/SpaceCreateRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/space/entity/Space.java
  backend/src/main/java/com/likelion/loco_project/global/config/WebSocketConfig.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/chat-test/page.tsx
  frontend/src/components/chat/chat.tsx
  frontend/src/components/chat/chatdelete.tsx
  frontend/src/components/chat/chatedit.tsx
  frontend/src/components/chat/chatroom.tsx
  frontend/src/components/chat/chatroomlist.tsx
Labels: feature

#26 [Feature/#21]회원 정보 수정, 물리삭제, 논리삭제 추가완료
  backend/src/main/java/com/likelion/loco_project/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/likelion/loco_project/domain/user/dto/LoginRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/user/entity/User.java
  backend/src/main/java/com/likelion/loco_project/domain/user/service/UserService.java
  backend/src/main/java/com/likelion/loco_project/global/config/SecurityConfig.java
  backend/src/main/resources/application.yml
Labels: feature

#27 [Feature/#24] 예약/결제 관련 기능 수정
  backend/src/main/java/com/likelion/loco_project/domain/guest/repository/GuestRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/controller/ApiV1PaymentController.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/dto/PaymentRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/dto/PaymentResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/entity/Payment.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/service/PaymentService.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/controller/ApiV1ReservationController.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/dto/ReservationRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/dto/ReservationResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/entity/Reservation.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/service/ReservationService.java
Labels: feature

#32 [Feature/#23] 게시판 이미지 추가 기능
  backend/build.gradle.kts
  backend/src/main/java/com/likelion/loco_project/domain/board/board/dto/BoardImageResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/dto/BoardRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/dto/BoardResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/entity/BoardImage.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/repository/BoardImageRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/service/BoardService.java
  backend/src/main/java/com/likelion/loco_project/domain/s3/S3Service.java
  backend/src/main/java/com/likelion/loco_project/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/likelion/loco_project/domain/user/dto/LoginRequestDto.java
  backend/src/main/java/com/likelion/loco_project/global/config/AwsS3Config.java
  backend/src/main/java/com/likelion/loco_project/global/config/SecurityConfig.java
  backend/src/main/resources/application-secret.yml.default
  backend/src/main/resources/application.yml
Labels: feature

#33 [Feature/#29] 토스페이먼츠 기능 작업
  backend/build.gradle.kts
  backend/src/main/java/com/likelion/loco_project/domain/payment/controller/ApiV1PaymentController.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/dto/TossPaymentRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/service/TossPaymentService.java
  backend/src/main/resources/application.yml
Labels: feature

#34 [Feature/#30] 호스트, 게스트 도메인 모델 및 api 기반 구현완료
  backend/src/main/java/com/likelion/loco_project/domain/guest/controller/ApiV1GuestController.java
  backend/src/main/java/com/likelion/loco_project/domain/guest/dto/GuestRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/guest/dto/GuestResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/guest/entity/Guest.java
  backend/src/main/java/com/likelion/loco_project/domain/guest/repository/GuestRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/guest/service/GuestService.java
  backend/src/main/java/com/likelion/loco_project/domain/host/controller/ApiV1HostController.java
  backend/src/main/java/com/likelion/loco_project/domain/host/dto/HostRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/host/dto/HostResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/host/entity/Host.java
  backend/src/main/java/com/likelion/loco_project/domain/host/service/HostService.java
  backend/src/main/java/com/likelion/loco_project/domain/user/dto/UserRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/user/entity/User.java
  backend/src/main/java/com/likelion/loco_project/domain/user/service/UserService.java
Labels: feature

#41 [Feature/#37] 공간 등록 페이지 (호스트 게시판) 기능
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/components/ThemeToggle.tsx
  frontend/src/app/context/ThemeContext.tsx
  frontend/src/app/host/[id]/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/spaces/[id]/page.tsx
  frontend/src/app/spaces/page.tsx
  frontend/src/app/spaces/register/page.tsx
Labels: feature

#40 [Feature/#36] 공간 작성 프론트
  backend/src/main/java/com/likelion/loco_project/domain/reservation/repository/ReservationRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/space/dto/SpaceCreateRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/space/dto/SpaceResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/space/dto/SpaceUpdateRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/space/entity/Space.java
  backend/src/main/java/com/likelion/loco_project/domain/space/entity/SpaceType.java
  backend/src/main/java/com/likelion/loco_project/domain/space/repository/SpaceRepository.java
  backend/src/main/java/com/likelion/loco_project/global/config/KakaoMapConfig.java
  backend/src/main/resources/application.yml
  frontend/.env
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/chat-test/page.tsx
  frontend/src/app/host/layout.tsx
  frontend/src/app/host/login/page.tsx
  frontend/src/app/host/page.tsx
  frontend/src/app/host/signup/page.tsx
  frontend/src/app/host/space/register/details/page.tsx
  frontend/src/app/host/space/register/page.tsx
  frontend/src/components/header/hostheader.tsx
  frontend/src/components/map/KakaoMap.tsx
  frontend/src/components/space/ImageUploader.tsx
  frontend/src/components/space/SpaceTypeSelector.tsx
  frontend/src/components/space/TagInput.tsx
Labels: feature

#42 [Feature/#38] 결제/예약 파트 프론트 작업
  frontend/package.json
  frontend/src/app/payment/fail/page.tsx
  frontend/src/app/payment/page.tsx
  frontend/src/app/payment/success/page.tsx
  frontend/src/app/reservation/page.tsx
  frontend/src/components/Calendar.tsx
  frontend/src/components/SpaceList.tsx
  frontend/src/components/TimeSelector.tsx
  frontend/tsconfig.json
Labels: feature

#44 Fix/#43
  frontend/package.json
Labels: fix

#46 [Feature/#45] 게스트 메인, 로그인, 회원가입 페이지 구현
  frontend/next.config.js
  frontend/src/app/globals.css
  frontend/src/app/login/page.module.css
  frontend/src/app/login/page.tsx
  frontend/src/app/page.module.css
  frontend/src/app/page.tsx
  frontend/src/app/signup/page.module.css
  frontend/src/app/signup/page.tsx
  frontend/src/components/Calendar.tsx
  frontend/src/components/calendar.module.css
  frontend/src/components/category-grid.module.css
  frontend/src/components/category-grid.tsx
  frontend/src/components/category-nav.module.css
  frontend/src/components/category-nav.tsx
  frontend/src/components/footer.module.css
  frontend/src/components/footer.tsx
  frontend/src/components/header.module.css
  frontend/src/components/header.tsx
  frontend/src/components/hero.module.css
  frontend/src/components/hero.tsx
Labels: feature

#58 [Feature/#51] Guest 프론트 작업(메인, 로그인, 회원가입) 완료
  frontend/package.json
  frontend/src/app/login/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/signup/page.tsx
Labels: feature

#56 [Feature/#50] 공간 작성 백앤드 프론트 연결
  backend/src/main/java/com/likelion/loco_project/domain/host/controller/ApiV1HostController.java
  backend/src/main/java/com/likelion/loco_project/domain/space/controller/ApiV1SpaceController.java
  backend/src/main/java/com/likelion/loco_project/domain/space/dto/SpaceCreateRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/space/dto/SpaceResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/space/entity/Space.java
  backend/src/main/java/com/likelion/loco_project/domain/space/service/SpaceService.java
  backend/src/main/java/com/likelion/loco_project/global/config/WebConfig.java
  frontend/src/app/host/layout.tsx
  frontend/src/app/host/page.module.css
  frontend/src/app/host/space/edit/[id]/page.tsx
  frontend/src/app/host/space/register/complete/page.module.css
  frontend/src/app/host/space/register/complete/page.tsx
  frontend/src/app/host/space/register/details/page.module.css
  frontend/src/app/host/space/register/details/page.tsx
  frontend/src/app/host/space/register/page.module.css
  frontend/src/components/header/hostheader.module.css
  frontend/src/components/map/KakaoMap.tsx
Labels: feature

#54 [Feature/#53] 예약 결제 확인 및 로깅
  .gradle/8.13/checksums/checksums.lock
  .gradle/8.13/executionHistory/executionHistory.lock
  .gradle/8.13/fileChanges/last-build.bin
  .gradle/8.13/fileHashes/fileHashes.lock
  .gradle/8.13/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
  backend/src/main/java/com/likelion/loco_project/domain/payment/dto/PaymentRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/service/PaymentService.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/dto/ReservationRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/service/ReservationService.java
Labels: feature

#60 [Feature/#57] fix: 결제, 예약 관련 오류 해결 - develop 즉시 병합
  backend/src/main/java/com/likelion/loco_project/domain/payment/service/PaymentService.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/dto/ReservationRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/service/ReservationService.java
  backend/src/main/java/com/likelion/loco_project/domain/space/dto/SpaceCreateRequestDto.java
Labels: fix

#62 [Feature/#57] H2 DB -> MySQL DB 마이그레이션
  backend/src/main/resources/application.yml
Labels: update

#65 [Fix/#2] 결제, 예약 관련 마이페이지 기능
  backend/src/main/java/com/likelion/loco_project/domain/mypage/controller/MyPageController.java
  backend/src/main/java/com/likelion/loco_project/domain/mypage/service/MyPageService.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/dto/PaymentResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/dto/ReservationResponseDto.java
  frontend/src/app/mypage/page.tsx
Labels: fix

#76 [Feature/#67] 관리자 페이지 기능 추가
  backend/src/main/java/com/likelion/loco_project/domain/admin/controller/AdminDashboardController.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/dto/DashboardPendingSpaceDto.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/dto/DashboardRecentReservationDto.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/dto/DashboardReservationChartDto.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/dto/DashboardSalesChartDto.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/dto/DashboardSpaceTypeDistributionDto.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/dto/DashboardSummaryDto.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/service/AdminDashboardService.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/repository/PaymentRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/repository/ReservationRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/space/entity/SpaceStatus.java
  backend/src/main/java/com/likelion/loco_project/domain/space/repository/SpaceRepository.java
  frontend/package-lock.json
  frontend/package.json
  frontend/public/logo-light.PNG
  frontend/public/logo.png
  frontend/src/app/admin/dashboard/page.tsx
  frontend/src/app/admin/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/signup/page.tsx
  frontend/src/components/AdminLayout.tsx
  frontend/src/components/Card.tsx
  frontend/src/components/Logo.tsx
Labels: feature

#78 [Feature/#68] 알림 엔티티 추가
  backend/src/main/java/com/likelion/loco_project/domain/notification/controller/ApiV1NotificationController.java
  backend/src/main/java/com/likelion/loco_project/domain/notification/dto/NotificationResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/notification/entity/Notification.java
  backend/src/main/java/com/likelion/loco_project/domain/notification/entity/NotificationType.java
  backend/src/main/java/com/likelion/loco_project/domain/notification/entity/UserNotificationSetting.java
  backend/src/main/java/com/likelion/loco_project/domain/notification/repository/NotificationRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/notification/service/NotificationService.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/entity/Reservation.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/entity/ReservationStatus.java
  backend/src/main/java/com/likelion/loco_project/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/likelion/loco_project/domain/user/entity/User.java
  backend/src/main/java/com/likelion/loco_project/domain/user/service/UserService.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/host/testpage/page.module.css
  frontend/src/app/host/testpage/page.tsx
  frontend/src/components/header/hostheader.module.css
  frontend/src/components/header/hostloginheader.tsx
  frontend/src/components/notification/notification.module.css
  frontend/src/components/notification/notification.tsx
  frontend/src/lib/axios.ts
Labels: feature

#79 [Feature/#75] ⭐중간 피드백 반영 내용
  backend/src/main/java/com/likelion/loco_project/LocoProjectApplication.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/controller/AdminController.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/controller/AdminDashboardController.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/dto/AdminLoginRequest.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/repository/AdminRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/service/AdminService.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/entity/Board.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/repository/BoardImageRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/service/BoardService.java
  backend/src/main/java/com/likelion/loco_project/domain/board/comment/dto/CommentDto.java
  backend/src/main/java/com/likelion/loco_project/domain/board/comment/repository/CommentRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/repository/ChatMessageRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/repository/ChatRoomRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/service/ChatMessageService.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/service/ChatRoomService.java
  backend/src/main/java/com/likelion/loco_project/domain/guest/controller/ApiV1GuestController.java
  backend/src/main/java/com/likelion/loco_project/domain/guest/dto/GuestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/guest/repository/GuestRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/guest/service/GuestService.java
  backend/src/main/java/com/likelion/loco_project/domain/home/main/controller/MainController.java
  backend/src/main/java/com/likelion/loco_project/domain/host/controller/ApiV1HostController.java
  backend/src/main/java/com/likelion/loco_project/domain/host/dto/HostDto.java
  backend/src/main/java/com/likelion/loco_project/domain/host/service/HostService.java
  backend/src/main/java/com/likelion/loco_project/domain/mypage/controller/MyPageController.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/controller/ApiV1PaymentController.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/repository/PaymentRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/repository/ReservationRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/space/controller/ApiV1SpaceController.java
  backend/src/main/java/com/likelion/loco_project/domain/space/repository/SpaceRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/space/service/SpaceService.java
  backend/src/main/java/com/likelion/loco_project/domain/user/dto/UserDto.java
  backend/src/main/java/com/likelion/loco_project/domain/user/service/UserService.java
Labels: update

#80 [Feature/#72,77] 게스트 회원가입 및 로그인, 호스트 로그인 기능 추가 및 테스트
  backend/src/main/java/com/likelion/loco_project/domain/host/controller/ApiV1HostController.java
  backend/src/main/java/com/likelion/loco_project/domain/host/service/HostService.java
  backend/src/main/java/com/likelion/loco_project/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/likelion/loco_project/domain/user/dto/LoginRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/user/dto/LoginResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/user/dto/UserRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/user/entity/User.java
  backend/src/main/java/com/likelion/loco_project/domain/user/service/UserService.java
  backend/src/main/java/com/likelion/loco_project/global/jwt/JwtUtil.java
  backend/src/main/resources/application.yml
  frontend/src/app/host/[id]/page.tsx
  frontend/src/app/host/login/page.tsx
  frontend/src/app/host/signup/page.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/signup/page.tsx
  frontend/src/components/header/hostheader.tsx
  frontend/src/services/api.ts
Labels: feature

#83 [Feature/#71] 공간 검색 기능 추가
  backend/src/main/java/com/likelion/loco_project/domain/space/controller/ApiV1SpaceController.java
  backend/src/main/java/com/likelion/loco_project/domain/space/dto/SpaceSearchDto.java
  backend/src/main/java/com/likelion/loco_project/domain/space/repository/SpaceRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/space/service/SpaceService.java
  frontend/public/sample-space-1.jpg
  frontend/public/sample-space-2.jpg
  frontend/public/sample-space-3.jpg
  frontend/src/app/layout.tsx
  frontend/src/app/spaces/page.tsx
  frontend/src/app/spaces/search/page.tsx
  frontend/src/components/header/MainHeader.tsx
  frontend/src/components/header/header.tsx
  frontend/src/components/space/SearchForm.tsx
  frontend/src/components/space/SpaceCard.tsx
  frontend/src/components/space/SpaceFilter.tsx
  frontend/src/components/space/SpaceSearch.tsx
Labels: feature

#84 [Fix/#82] 호스트 로그인 유지 실패 관련 버그 픽스
  frontend/next.config.js
  frontend/src/app/api/auth/check/route.ts
  frontend/src/app/host/login/page.tsx
  frontend/src/components/header/hostheader.tsx
  frontend/src/services/api.ts
Labels: fix

#85 [Feature/#69, 70] 후기 작성, 신고기능, 평점기능 추가
  backend/src/main/java/com/likelion/loco_project/domain/guestRating/controller/GuestRatingController.java
  backend/src/main/java/com/likelion/loco_project/domain/guestRating/dto/GuestRatingRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/guestRating/dto/GuestRatingResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/guestRating/entity/GuestRating.java
  backend/src/main/java/com/likelion/loco_project/domain/guestRating/repository/GuestRatingRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/guestRating/service/GuestRatingService.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/entity/PaymentMethod.java
  backend/src/main/java/com/likelion/loco_project/domain/report/controller/ReportController.java
  backend/src/main/java/com/likelion/loco_project/domain/report/dto/ReportRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/report/dto/ReportResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/report/entity/Report.java
  backend/src/main/java/com/likelion/loco_project/domain/report/entity/ReportReason.java
  backend/src/main/java/com/likelion/loco_project/domain/report/entity/ReportType.java
  backend/src/main/java/com/likelion/loco_project/domain/report/repository/ReportRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/report/service/ReportService.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/dto/ReservationResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/review/controller/GuestReviewController.java
  backend/src/main/java/com/likelion/loco_project/domain/review/dto/ReviewRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/review/dto/ReviewResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/review/entity/Review.java
  backend/src/main/java/com/likelion/loco_project/domain/review/repository/ReviewReposityro.java
  backend/src/main/java/com/likelion/loco_project/domain/review/service/ReviewService.java
Labels: feature

#91 [Feature/#68] 알람 필터 백엔드, 프론트엔드 추가
  backend/src/main/java/com/likelion/loco_project/domain/notification/controller/ApiV1NotificationController.java
  backend/src/main/java/com/likelion/loco_project/domain/notification/dto/NotificationSettingResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/notification/entity/UserNotificationSetting.java
  backend/src/main/java/com/likelion/loco_project/domain/notification/repository/UserNotificationSettingRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/notification/service/NotificationService.java
  backend/src/main/java/com/likelion/loco_project/domain/notification/service/NotificationSettingService.java
  backend/src/main/java/com/likelion/loco_project/domain/space/controller/ApiV1SpaceController.java
  backend/src/main/java/com/likelion/loco_project/global/config/WebSocketConfig.java
  frontend/src/app/host/page.tsx
  frontend/src/app/host/spaces/edit/[id]/page.tsx
  frontend/src/app/host/spaces/register/complete/page.module.css
  frontend/src/app/host/spaces/register/complete/page.tsx
  frontend/src/app/host/spaces/register/details/page.module.css
  frontend/src/app/host/spaces/register/details/page.tsx
  frontend/src/app/host/spaces/register/page.module.css
  frontend/src/app/host/spaces/register/page.tsx
  frontend/src/app/settings/notifications/notification.module.css
  frontend/src/app/settings/notifications/notification.tsx
  frontend/src/app/settings/page.module.css
  frontend/src/app/settings/page.tsx
  frontend/src/components/chat/chat.tsx
  frontend/src/components/chat/chatroom.tsx
  frontend/src/components/header/hostheader.tsx
  frontend/src/components/header/hostloginheader.tsx
  frontend/src/components/notification/notification.tsx
Labels: feature

#96 [Feature/#73] 회원가입 이메일 인증 번호 기능 추가
  backend/build.gradle.kts
  backend/src/main/java/com/likelion/loco_project/domain/auth/EmailAuthManager.java
  backend/src/main/java/com/likelion/loco_project/domain/mail/mail/service/MailService.java
  backend/src/main/java/com/likelion/loco_project/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/likelion/loco_project/domain/user/service/UserService.java
  backend/src/main/java/com/likelion/loco_project/global/config/EmailConfig.java
  backend/src/main/java/com/likelion/loco_project/global/exception/BusinessLogicException.java
  backend/src/main/java/com/likelion/loco_project/global/exception/ExceptionCode.java
  backend/src/main/java/com/likelion/loco_project/global/redis/RedisService.java
  backend/src/main/resources/application.yml
  frontend/src/app/host/signup/page.module.css
  frontend/src/app/host/signup/page.tsx
  frontend/src/app/signup/page.tsx
  frontend/src/components/emailverification/EmailVerfificationModal.tsx
  frontend/src/components/emailverification/EmailVerification.module.css
  frontend/src/components/emailverification/EmailVerificationButton.tsx
  frontend/src/lib/axios.ts
Labels: feature

#99 [Feature/#98] rate/report/review frontend part
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/RatingStars.tsx
  frontend/src/components/ReportForm.tsx
  frontend/src/components/ReviewForm.tsx
  frontend/src/components/ReviewList.tsx
  frontend/src/lib/api/review.ts
  frontend/src/types/review.ts
Labels: feature

#100 feature/찜하기 백앤드와 프론트 마이페이지에서 찜 목록(#92)
  backend/src/main/java/com/likelion/loco_project/domain/review/repository/ReviewRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/space/controller/ApiV1SpaceController.java
  backend/src/main/java/com/likelion/loco_project/domain/space/dto/SpaceResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/space/entity/Space.java
  backend/src/main/java/com/likelion/loco_project/domain/space/service/SpaceService.java
  backend/src/main/java/com/likelion/loco_project/domain/user/entity/User.java
  frontend/src/app/mypage/page.tsx
  frontend/src/components/FavoriteButton/FavoriteButton.tsx
Labels: feature

#102 [Feature/#74] AWS S3 + 호스트 게시판 이미지 업로드 폼 연결
  frontend/src/app/host/spaces/register/details/page.tsx
  frontend/src/app/spaces/page.tsx
  frontend/src/app/spaces/register/page.tsx
  frontend/src/components/space/ImageUploader.tsx
  frontend/src/services/s3Service.ts
Labels: feature

#111 [Fix/#109] 공간 등록 페이지 개선 및 호스트 로그인 관련
  frontend/src/app/host/page.tsx
  frontend/src/app/host/spaces/register/complete/page.tsx
  frontend/src/app/host/spaces/register/page.tsx
  frontend/src/middleware.ts
  frontend/src/services/api.ts
Labels: fix

#112 [Refactor/#86] 전체 Swagger 관련 개선
  backend/src/main/java/com/likelion/loco_project/domain/admin/controller/AdminController.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/controller/AdminDashboardController.java
  backend/src/main/java/com/likelion/loco_project/domain/board/board/controller/ApiV1BoardController.java
  backend/src/main/java/com/likelion/loco_project/domain/board/comment/controller/ApiV1CommentController.java
  backend/src/main/java/com/likelion/loco_project/domain/chat/controller/ApiV1ChatController.java
  backend/src/main/java/com/likelion/loco_project/domain/guest/controller/ApiV1GuestController.java
  backend/src/main/java/com/likelion/loco_project/domain/guestRating/controller/GuestRatingController.java
  backend/src/main/java/com/likelion/loco_project/domain/host/controller/ApiV1HostController.java
  backend/src/main/java/com/likelion/loco_project/domain/host/service/HostService.java
  backend/src/main/java/com/likelion/loco_project/domain/mypage/controller/MyPageController.java
  backend/src/main/java/com/likelion/loco_project/domain/notification/controller/ApiV1NotificationController.java
  backend/src/main/java/com/likelion/loco_project/domain/payment/controller/ApiV1PaymentController.java
  backend/src/main/java/com/likelion/loco_project/domain/report/controller/ReportController.java
  backend/src/main/java/com/likelion/loco_project/domain/reservation/controller/ApiV1ReservationController.java
  backend/src/main/java/com/likelion/loco_project/domain/review/controller/GuestReviewController.java
  backend/src/main/java/com/likelion/loco_project/domain/space/controller/ApiV1SpaceController.java
  backend/src/main/java/com/likelion/loco_project/domain/space/controller/ApiV1SpaceImageController.java
  backend/src/main/java/com/likelion/loco_project/domain/space/controller/PlaceholderImageController.java
  backend/src/main/java/com/likelion/loco_project/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/likelion/loco_project/domain/user/dto/LoginResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/user/service/UserService.java
Labels: update

#121 [Feature/#118] Jwt 업데이트 및 게스트 호스트 로그인 가능하게 변경
  backend/src/main/java/com/likelion/loco_project/domain/host/controller/ApiV1HostController.java
  backend/src/main/java/com/likelion/loco_project/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/likelion/loco_project/domain/user/controller/AuthController.java
  backend/src/main/java/com/likelion/loco_project/domain/user/dto/LoginResponseDto.java
  backend/src/main/java/com/likelion/loco_project/global/config/SecurityConfig.java
  backend/src/main/java/com/likelion/loco_project/global/config/WebSocketConfig.java
  backend/src/main/java/com/likelion/loco_project/global/jwt/JwtHandshakeInterceptor.java
  backend/src/main/java/com/likelion/loco_project/global/jwt/JwtProvider.java
  backend/src/main/java/com/likelion/loco_project/global/jwt/JwtTokenProvider.java
  backend/src/main/java/com/likelion/loco_project/global/jwt/JwtUtil.java
  frontend/src/app/host/login/page.tsx
  frontend/src/app/login-success/page.tsx
  frontend/src/app/login/page.tsx
Labels: update

#123 Update: ApiV1UserController.java
  backend/src/main/java/com/likelion/loco_project/domain/user/controller/ApiV1UserController.java
Labels: update

#125 [Fix/#113] 공간 DB 연동 로직
  backend/src/main/java/com/likelion/loco_project/domain/host/controller/ApiV1HostController.java
  backend/src/main/java/com/likelion/loco_project/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/likelion/loco_project/domain/user/dto/LoginResponseDto.java
  frontend/src/app/host/head.tsx
  frontend/src/app/host/layout.tsx
  frontend/src/app/host/page.tsx
  frontend/src/app/host/spaces/register/details/page.tsx
  frontend/src/app/login/page.tsx
  frontend/src/components/header/hostheader.tsx
  frontend/src/components/notification/notification.tsx
  frontend/src/types/space/index.ts
Labels: fix

#128 [Fix/#126] 공간 등록 (백엔드, 프론트엔드) 테스트 및 DB 등록 성공
  backend/src/main/java/com/likelion/loco_project/domain/host/repository/HostRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/space/controller/ApiV1SpaceController.java
  backend/src/main/java/com/likelion/loco_project/domain/space/controller/ApiV1SpaceImageController.java
  backend/src/main/java/com/likelion/loco_project/domain/space/dto/SpaceCreateRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/space/service/SpaceService.java
  backend/src/main/java/com/likelion/loco_project/global/config/SecurityConfig.java
  backend/src/main/java/com/likelion/loco_project/global/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/likelion/loco_project/global/util/GlobalUtil.java
  backend/src/main/resources/application.yml
  frontend/src/app/components/HostNavbar.tsx
  frontend/src/app/components/Navbar.tsx
  frontend/src/app/host/layout.tsx
  frontend/src/app/host/login/page.tsx
  frontend/src/app/host/page.tsx
  frontend/src/app/host/spaces/page.tsx
  frontend/src/app/host/spaces/register/details/page.tsx
  frontend/src/app/host/testpage/page.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/settings/notifications/notification.tsx
  frontend/src/components/header/hostheader.tsx
  frontend/src/context/AuthContext.tsx
  test_image.jpg
Labels: fix

#130 [Feature/#122] feat: 카카오 로그인 연동2
  backend/build.gradle.kts
  backend/src/main/java/com/likelion/loco_project/domain/user/service/UserService.java
  backend/src/main/java/com/likelion/loco_project/global/config/SecurityConfig.java
  backend/src/main/java/com/likelion/loco_project/global/oauth/CustomOAuth2UserService.java
  backend/src/main/java/com/likelion/loco_project/global/oauth/LoginRedirectController.java
  backend/src/main/java/com/likelion/loco_project/global/oauth/OAuth2AuthenticationSuccessHandler.java
  backend/src/main/java/com/likelion/loco_project/global/oauth/PrincipalOAuth2User.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application.yml
  frontend/src/app/api/auth/check/route.ts
  frontend/src/app/layout.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/oauth2/success/page.tsx
  frontend/src/app/signup/page.tsx
Labels: feature

#135 [Feature/#122] 다크모드 뺀 버전 커밋
  backend/build.gradle.kts
  backend/src/main/java/com/likelion/loco_project/domain/host/controller/ApiV1HostController.java
  backend/src/main/java/com/likelion/loco_project/domain/host/repository/HostRepository.java
  backend/src/main/java/com/likelion/loco_project/domain/space/controller/ApiV1SpaceController.java
  backend/src/main/java/com/likelion/loco_project/domain/space/controller/ApiV1SpaceImageController.java
  backend/src/main/java/com/likelion/loco_project/domain/space/dto/SpaceCreateRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/space/service/SpaceService.java
  backend/src/main/java/com/likelion/loco_project/domain/user/controller/ApiV1UserController.java
  backend/src/main/java/com/likelion/loco_project/domain/user/dto/LoginResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/user/service/UserService.java
  backend/src/main/java/com/likelion/loco_project/global/config/SecurityConfig.java
  backend/src/main/java/com/likelion/loco_project/global/jwt/JwtAuthenticationFilter.java
  backend/src/main/java/com/likelion/loco_project/global/oauth/CustomOAuth2UserService.java
  backend/src/main/java/com/likelion/loco_project/global/oauth/LoginRedirectController.java
  backend/src/main/java/com/likelion/loco_project/global/oauth/OAuth2AuthenticationSuccessHandler.java
  backend/src/main/java/com/likelion/loco_project/global/oauth/PrincipalOAuth2User.java
  backend/src/main/java/com/likelion/loco_project/global/util/GlobalUtil.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application.yml
  frontend/src/app/api/auth/check/route.ts
  frontend/src/app/components/HostNavbar.tsx
  frontend/src/app/components/Navbar.tsx
  frontend/src/app/host/head.tsx
  frontend/src/app/host/login/page.tsx
  frontend/src/app/host/page.tsx
  frontend/src/app/host/spaces/page.tsx
  frontend/src/app/host/spaces/register/details/page.tsx
  frontend/src/app/host/testpage/page.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/oauth2/success/page.tsx
  frontend/src/app/settings/notifications/notification.tsx
  frontend/src/app/signup/page.tsx
  frontend/src/components/MainHeader.tsx
  frontend/src/components/notification/notification.tsx
  frontend/src/context/AuthContext.tsx
  frontend/src/types/space/index.ts
Labels: feature

#147 [Feature/#89] 관리자 페이지 - 전체 사용자 권한 관리 추가
  backend/src/main/java/com/likelion/loco_project/domain/admin/controller/AdminUserController.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/dto/UpdateRoleRequestDto.java
  backend/src/main/java/com/likelion/loco_project/domain/user/controller/AuthController.java
  backend/src/main/java/com/likelion/loco_project/domain/user/dto/UserResponseDto.java
  backend/src/main/java/com/likelion/loco_project/domain/user/entity/User.java
  backend/src/main/java/com/likelion/loco_project/domain/user/entity/UserType.java
  backend/src/main/java/com/likelion/loco_project/domain/user/service/UserService.java
  backend/src/main/java/com/likelion/loco_project/global/exception/ExceptionCode.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/admin/dashboard/page.tsx
  frontend/src/app/admin/layout.tsx
  frontend/src/app/admin/users/page.tsx
  frontend/src/app/host/layout.tsx
  frontend/src/components/admin/UserManagement.tsx
  frontend/src/components/header/hostheader.tsx
  frontend/src/context/AuthContext.tsx
  frontend/src/lib/axios.ts
Labels: feature

#152 [Fix/#150] 관리자페이지 관련 오류 해결
  backend/build.gradle.kts
  backend/src/main/java/com/likelion/loco_project/domain/admin/controller/AdminDashboardController.java
  backend/src/main/java/com/likelion/loco_project/domain/admin/controller/AdminUserController.java
  backend/src/main/java/com/likelion/loco_project/global/config/SecurityConfig.java
  frontend/src/app/admin/reservations/page.tsx
  frontend/src/components/admin/UserManagement.tsx
  frontend/src/lib/axios.ts
Labels: fix

#154 [Feature/#153] 공간보기 메인과 연결, 공간상세페이지 구현
  frontend/next.config.js
  frontend/public/placeholder.png
  frontend/public/placeholder.svg
  frontend/src/app/host/profile/changepassword/page.tsx
  frontend/src/app/host/signup/page.tsx
  frontend/src/app/host/spaces/edit/[id]/page.tsx
  frontend/src/app/spaces/[id]/page.tsx
  frontend/src/app/spaces/all/page.tsx
  frontend/src/app/spaces/search/page.tsx
  frontend/src/components/header/header.tsx
  frontend/src/components/space/SpaceCard.tsx
Labels: feature

#156 fix: 호스트 소셜로그인 할때에 게스트 회원가입으로 가는거 수정 (#151)
  backend/src/main/java/com/likelion/loco_project/domain/user/dto/OAuth2RedirectDto.java
  backend/src/main/java/com/likelion/loco_project/global/config/SecurityConfig.java
  backend/src/main/java/com/likelion/loco_project/global/oauth/HostOAuth2Controller.java
  backend/src/main/java/com/likelion/loco_project/global/oauth/OAuth2AuthenticationSuccessHandler.java
  frontend/src/app/host/login/page.tsx
  frontend/src/app/host/profile/page.module.css
  frontend/src/app/host/profile/page.tsx
  frontend/src/app/host/signup/page.module.css
  frontend/src/app/host/signup/page.tsx
  frontend/src/app/host/spaces/register/complete/page.tsx
  frontend/src/components/header/hostheader.tsx
Labels: fix
